- randomgen_function:
    call: http.get
    args:
        url: https://randomgen-function-vhzkgg5nba-uc.a.run.app
    result: randomgen_result
- multiply_function:
    call: http.post
    args:
        url: https://multiply-function-vhzkgg5nba-uc.a.run.app
        body:
            input: ${randomgen_result.body.random}
    result: multiply_result
- return_result:
    return: ${multiply_result}